# Generated by Django 5.2.4 on 2025-07-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('branch', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
